name: Create releases for Linux, Windows and MacOS & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-release:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.9
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        poetry-version: [ 1.1.6 ]
        os: [ ubuntu-20.04, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        if: matrix.os != 'macOS-latest'
        with:
          python-version: ${{ matrix.python-version }}

      # Based on: https://github.com/actions/virtual-environments/issues/1256#issuecomment-770270252
      - name: Set up Python for macOS
        if: matrix.os == 'macOS-latest'
        run: |
          curl https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-macosx10.9.pkg -o "python.pkg"
          sudo installer -pkg python.pkg -target /
          echo "/Library/Frameworks/Python.framework/Versions/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}.9

      - name: Install poetry
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install innosetup
          fi
          pip3 install poetry==${{ matrix.poetry-version }}

      - name: Disable virtualenvs
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Build executable
        run: pyinstaller --clean pyinstaller.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aw-watcher-utilization-${{ matrix.os }}
          path: dist/aw-watcher-utilization
